### ISSUE TITLE
iOS San Francisco: Different font sizes in the same paragraph ends up with incorrect character spacing

### ISSUE THREAD

**Issue by daltonks** [toptensoftware/RichTextKit#24] opened 2020-10-24 17:07 UTC
Heyo 👋

This issue appears on iOS when using "San Francisco" as the font family.

In the picture below, the characters for the formatted date (10/17/2020 11:40 AM) are spread too far apart. Looks like this occurs because the date string is added to a paragraph that already has text of a bigger font size.

![image](https://user-images.githubusercontent.com/1009458/97087566-b51f6500-15f0-11eb-8f00-24d885098011.png)

Compare that to this, where I added a new paragraph before the formatted date. The character spacing is correct.

![image](https://user-images.githubusercontent.com/1009458/97087662-442c7d00-15f1-11eb-8da0-fcde8b9ebeb2.png)

**Comment by toptensoftware** [comment] 2020-10-26 00:20
Hi Dalton,  thanks for reporting.  I'll probably need to reproduce here to fix. Some questions:

1. Does this only happen on iOS? (I don't have that dev platform setup and not keen to go down that route :))
2. How is the font of the preceding text being set.  ie: what is CreateRichString() doing in regard to setting fonts and/or have you set a default font on the StyleManager?
3. Any chance this is a carry over effect from some preceeding text rendering.  ie: does this happen if you render that block of text and nothing else before hand?
4. Does this only happen with Segoe UI?

**Comment by daltonks** [comment] 2020-10-26 01:38
Sorry, Segoe UI is what I use for UWP, hah. It's actually San Francisco on iOS.
I am creating a reproduction repo atm! If you don't have a mac, you won't be able to reproduce it though, so I hope I can help out there somehow.
Thank you

**Comment by toptensoftware** [comment] 2020-10-26 02:07
I do have a mac, but everytime I need to do iOS development on it it seems like I spend about 3 days trying to get it to work :(

If you can make a really simple repo case that'd be handy.

btw: it looks like the font has letter spacing set on it.  What happens if you explicitly set the character spacing to 0.  

https://www.toptensoftware.com/richtextkit/ref/Topten.RichTextKit.RichString.LetterSpacing

**Comment by daltonks** [comment] 2020-10-26 02:52
I am actually able to reproduce it on UWP, Android, and iOS, so maybe it's reproducible everywhere.

[Here is where I draw to the canvas](https://github.com/daltonks/RichTextKit_Issue24/blob/main/RichTextKitIssue24/RichTextKitIssue24/MainPage.xaml.cs)

And here is the result on UWP (note that letterSpacing didn't change the look):
![image](https://user-images.githubusercontent.com/1009458/97129160-3586b880-170c-11eb-8dc5-39ec4c1e792c.png)

**Comment by toptensoftware** [comment] 2020-10-26 07:11
Hi Dalton,  thanks for help with this.  Should be fixed in build 134 which has been pushed to nuget and should appear shortly.

**Closed by toptensoftware** 2020-10-26 07:11 UTC

**Comment by daltonks** [comment] 2020-10-26 14:15
Thank you 🙂
